### PR TITLE
Fix Storyshots integration

### PR DESCRIPTION
**Pull request by jribeiro**
This PR fixes storyshots integration and jest snapshot testing.

This is essentially a clone of https://github.com/truffls/storybook-addon-intl/pull/2 PR but with test fixed. I opened this PR against the initial PR but haven't received any feedback so far.

### CODE REVIEW

**Comment by floriangosse** [comment]
Thank you for the PR. I was a little bit busy the last weeks and couldn't find time to check #2.

It would be nice if you could add an additional test case for the change. Thanks. :)

**Comment by jribeiro** [comment]
Thanks @floriangosse. On it.

**Comment by jribeiro** [comment]
@floriangosse I've added a simple test to ensure that the change is working as expected. Let me know if you require any other change

**Comment by floriangosse** [comment]
Thank you. I will merge it. :)

**Comment by floriangosse** [comment]
I published the new version. :)

**Comment by jribeiro** [comment]
Ace. Thanks a lot

**Pull request merged**
