### PR TITLE
Add demo of storybook to readme, build to package.json

### PR DESCRIPTION
**Pull request by ezralalonde**
This depends on having an updated `gh-pages` branch, so that https://truffls.github.io/storybook-addon-intl is a valid url.

### CODE REVIEW

**Comment by ezralalonde** [comment]
I don't have access to create a `gh-pages` branch on truffls/storybook-addon-intl, but I have a branch at https://github.com/ezralalonde/storybook-addon-intl/tree/gh-pages

Create a blank `gh-pages` branch, and I can make another PR with the necessary content. Not sure if there's a better way.

**Comment by floriangosse** [comment]
That is a nice improvement. I think we can make it even better by utilizing GitHub Actions to run automated deployments.

I've used `peaceiris/actions-gh-pages@v2.5.0` in another project to deploy automatically when a change was pushed to the master branch. Maybe we can limit that to tags only.

I think it makes sense that a project maintainer has a look into that as it can be hard to test GitHub Actions.

What do you think about it?

**Comment by ezralalonde** [comment]
Sounds good to me.

**Comment by floriangosse** [comment]
I'll close this as we never made any further progress on that part. And right now I don't have the time to setup the needed actions to do automated deployments. 😕

**Pull request closed without merging**
